### ISSUE TITLE
画面の大枠を作成

### ISSUE THREAD

**Issue by mk2** [esm-bits/spring-jdbc-ui#8]
- どのコンポーネントフレームワークに乗るか（もしくは乗らないか）
  - ElmentUI
  - Vuetify
  - etc

**Comment by mk2** [comment]
今の所の想定画面モック

![3](https://user-images.githubusercontent.com/747840/45993332-63cae180-c0c9-11e8-9ac8-8a67978bfb75.PNG)

**Comment by mk2** [comment]
@fossamagna 今こんな感じの画面になっているのですが、想定しているのと違うとかあったら言ってもらえると 🙇 

<img width="1257" alt="2018-10-23 14 03 11" src="https://user-images.githubusercontent.com/747840/47336878-6884b480-d6cc-11e8-873a-f3dc5041686e.png">

クエリ作成・クエリ実行ボタンを追加したら一旦PRを出す予定です。

**Comment by fossamagna** [comment]
@mk2 画面の大枠はそんなイメージです。
ちょっと気になった点が2つあります。
- Sprint じゃなくて Spring
- tableName のところには何が表示されるんだろう？

**Comment by mk2** [comment]
@fossamagna tableNameはダミーデータで出しているだけです。そこがクエリパラメータ編集エリアになります。

**Comment by fossamagna** [comment]
@mk2 画面左側は`名前をつけてクエリを保存で機能`で作ったクエリの一覧ですかね？
その場合、名前ってどこで入力しましょうか？クエリの上とかにテキストフィールド追加とかかなー。

**Comment by mk2** [comment]
@fossamagna はい、左側はクエリ一覧になります。名前編集、そうですね、クエリ編集欄の上ですかねー

**Comment by mk2** [comment]
マージされたのでクローズ。
